// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBeHW6zpxrGB7quvP3vuCrVH0Ub_70_H8',
    appId: '1:651528352661:web:44d44a3b96311bd5777c9c',
    messagingSenderId: '651528352661',
    projectId: 'ghoreviewer',
    authDomain: 'ghoreviewer.firebaseapp.com',
    storageBucket: 'ghoreviewer.firebasestorage.app',
    measurementId: 'G-BW4D6GBHDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5yU8Y3S82HaHjI7L59_BGRj43pUHjaeI',
    appId: '1:651528352661:android:0b1e472f42bf3622777c9c',
    messagingSenderId: '651528352661',
    projectId: 'ghoreviewer',
    storageBucket: 'ghoreviewer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTN6gHPJwYy7jNipbFl4xY3lC_CJOho88',
    appId: '1:651528352661:ios:021249d637f6e8f1777c9c',
    messagingSenderId: '651528352661',
    projectId: 'ghoreviewer',
    storageBucket: 'ghoreviewer.firebasestorage.app',
    iosBundleId: 'care.gho.globalHealthOpinionRx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTN6gHPJwYy7jNipbFl4xY3lC_CJOho88',
    appId: '1:651528352661:ios:bde9930b58f20433777c9c',
    messagingSenderId: '651528352661',
    projectId: 'ghoreviewer',
    storageBucket: 'ghoreviewer.firebasestorage.app',
    iosBundleId: 'com.example.ghorxMobileAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBeHW6zpxrGB7quvP3vuCrVH0Ub_70_H8',
    appId: '1:651528352661:web:153b60ede67f7152777c9c',
    messagingSenderId: '651528352661',
    projectId: 'ghoreviewer',
    authDomain: 'ghoreviewer.firebaseapp.com',
    storageBucket: 'ghoreviewer.firebasestorage.app',
    measurementId: 'G-4MZDPMY4PR',
  );
}
